# Generated by Django 4.1 on 2022-08-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='my_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('type', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('gforms', models.TextField()),
                ('wlink', models.CharField(max_length=300)),
                ('donation_required', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('type', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
